// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
)

type Querier interface {
	DeleteExpiredTokens(ctx context.Context) error
	DeleteUser(ctx context.Context, id int64) error
	GetActiveRefreshTokenByID(ctx context.Context, id int64) (RefreshToken, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (int64, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (int64, error)
	ListUsers(ctx context.Context) ([]User, error)
	RevokeAllForUser(ctx context.Context, userID int64) error
	RevokeRefreshToken(ctx context.Context, id int64) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
