FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/auth ./cmd/auth-service

FROM gcr.io/distroless/base-debian12
# Non-root user
USER 10001:10001
WORKDIR /app
COPY --from=build /out/auth /app/auth
# /secrets will be mounted read-only by docker-compose
EXPOSE 8080
ENTRYPOINT ["/app/auth"]