// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        int64       `json:"id"`
	ActorUser pgtype.Int8 `json:"actor_user"`
	Action    string      `json:"action"`
	Meta      []byte      `json:"meta"`
	CreatedAt time.Time   `json:"created_at"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	IssuedAt  time.Time          `json:"issued_at"`
	ExpiresAt time.Time          `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	Ua        string             `json:"ua"`
	Ip        netip.Addr         `json:"ip"`
}

type User struct {
	ID         int64          `json:"id"`
	Email      string         `json:"email"`
	FirstName  sql.NullString `json:"first_name"`
	LastName   sql.NullString `json:"last_name"`
	Password   string         `json:"password"`
	UserActive bool           `json:"user_active"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}
